root: true
parser: 'vue-eslint-parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
env:
  browser: true
  es2021: true
  node: true
settings:
  vue:
    version: detect
extends:
  - standard
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:vue/vue3-essential
  - '@vue/eslint-config-airbnb'
  - '@vue/eslint-config-typescript'
  - '@vue/eslint-config-prettier'
  - plugin:nuxt/recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:jsdoc/recommended
  - prettier
plugins:
  - '@typescript-eslint'
  - vue
  - import
  - jsdoc
  - prettier

rules:
  '@typescript-eslint/no-shadow': error
  '@typescript-eslint/no-unused-vars': error

  prettier/prettier: error

  vue/html-indent: off
  vue/html-closing-bracket-newline: off
  vue/singleline-html-element-content-newline: off
  vue/html-self-closing:
    - error
    - html:
        normal: never
        void: always

  max-nested-callbacks:
    - error
    - max: 4
  max-statements-per-line:
    - error
    - max: 1
  no-console: error
  no-empty-function: error
  no-inline-comments: error
  no-lonely-if: error
  no-shadow: off
  no-plusplus: off
  no-var: error
  no-implicit-coercion:
    - error
    - boolean: true
      number: true
  prefer-const: error
  semi:
    - error
    - never
  import/no-unresolved:
    - warn
    - ignore:
      - '^@/*'
      - '^~/*'
  import/prefer-default-export: 'off'
  import/no-deprecated: error
  import/named: error
  import/namespace: error
  import/default: error
  import/export: error
  import/extensions: off
  import/order:
    - error
    - newlines-between: always
      warnOnUnassignedImports: true
      groups:
        - builtin
        - external
        - internal
        - parent
        - sibling
        - index
        - object
        - type
      alphabetize:
        order: asc
