trailingComma: none

semi: false
endOfLine: auto

bracketSpacing: true
bracketSameLine: false

singleQuote: true
jsxSingleQuote: true
quoteProps: consistent

useTabs: false
tabWidth: 2

printWidth: 120

arrowParens: always
