extends:
- stylelint-config-standard
plugins:
  - stylelint-prettier
overrides:
- files:
  - "*.jsx"
  - "*.tsx"
  customSyntax: postcss-lit
rules:
  at-rule-no-unknown:
  - true
  - ignoreAtRules:
    - tailwind
    - apply
    - variants
    - responsive
    - screen
