extends:
  - stylelint-config-standard
plugins:
  - stylelint-prettier
overrides:
  - files:
    - '*.vue'
    customSyntax: postcss-lit
rules:
  at-rule-no-unknown:
    - true
    - ignoreAtRules:
      - tailwind
      - apply
      - variants
      - responsive
      - screen
