on:
  # Allows you to run this workflow manually from the Actions tab or through HTTP API
  schedule:
    - cron: '0 0 * * MON'
  workflow_dispatch:

jobs:
  sync:
    name: 'Submodules Sync'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.CI_TOKEN }}
        submodules: true
        fetch-depth: 0

    - name: Snyk Security
      uses: snyk/actions@0.4.0
