name: Snyk Security

on:
  # Allows you to run this workflow manually from the Actions tab or through HTTP API
  schedule:
    - cron: '0 0 * * MON'
  workflow_dispatch:

jobs:
  security:
      name: Snyk Security
      runs-on: ubuntu-latest

      steps:
        - name: Snyk
          uses: snyk/actions@0.4.0
